### ISSUE TITLE
Schedule function calls

### ISSUE THREAD

**Issue by goncalo-oliveira** [justfaas/justfaas#1]
This adds the possibility to invoke a function on an interval basis, by using a CRON expression. This is achieved by decorating a function with an annotation.

```yaml
apiVersion: justfaas.com/v1alpha1
kind: Function
metadata:
  name: hello
  annotations:
    # trigger function every minute
    justfaas.com/cron-expression: "*/1 * * * *"
spec:
  image: gcr.io/google-samples/hello-app:1.0
```

The easiest way to achieve this is to use a Kubernetes [CronJob](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/). We could use `curl` to invoke the gateway's proxy.

Something in the likes of

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl:latest
            imagePullPolicy: IfNotPresent
            args:
            - -s
            - -X
            - POST
            - http://gateway:8080/proxy/default/hello
```
